# Configuration for sentiment-bot - https://github.com/behaviorbot/sentiment-bot

# *Required* toxicity threshold between 0 and .99 with the higher numbers being the most toxic
# Anything higher than this threshold will be marked as toxic and commented on
sentimentBotToxicityThreshold: .75

Comment to reply with
sentimentBotReplyComment: >
  Please be sure to review the [Code of Conduct](https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md) and be respectful of other users. cc/ @EdoPlantinga
